version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq-broker 
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD","rabbitmq-diagnostics","-q","check_running"]
      interval: 5s 
      timeout: 5s 
      retries: 5
  app: 
    build: . 
    container_name: go-app 
    depends_on: 
      rabbitmq:
        condition: service_healthy
    environment: 
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
   
